imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: en }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: fr
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'MopaBootstrapBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        compass: ~
        sass: ~
        cssrewrite: ~
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        less:
            node: /usr/local/bin/node
            node_paths: [/usr/local/lib/node_modules]
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar

propel:
    path:       "%kernel.root_dir%/../vendor/propel"
    phing_path: "%kernel.root_dir%/../vendor/phing"

mopa_bootstrap:
    form:
        show_legend: true # default is true
        show_child_legend: true # default is true
        error_type: inline # or inline which is default

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    expressions: true
    secure_controllers:  true
    secure_all_services: false

fos_user:
    db_driver: propel
    firewall_name: main
    user_class: FOS\UserBundle\Propel\UserProxy
    propel_user_class: FOS\UserBundle\Propel\User

knp_menu:
    twig: true

admingenerator_generator:
    base_admin_template: AdmingeneratorGeneratorBundle::base_admin.html.twig
    use_propel: true
    use_doctrine_orm: false
    use_doctrine_odm: false
