imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: fr }
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:
      engines: ['twig']
      assets_version: 2
    default_locale:  %locale%
    session:         ~

stof_doctrine_extensions:
    default_locale: %locale%
    uploadable:
        default_file_path: %kernel.root_dir%/../web
    orm:
        default:
            timestampable: true
            translatable: true
            sluggable: true
            uploadable: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        domain: %domain%
    form:
        resources:
            - 'MopaBootstrapBundle:Form:fields.html.twig'

services:
    twig.extension.debug:
        class: Twig_Extensions_Extension_Debug
        tags:
            - { name: 'twig.extension' }

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: 'twig.extension' }

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        lessphp:
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            apply_to: "\.less$"
        cssrewrite: ~
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"

doctrine:
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

        mappings:
            gedmo_translatable:
                type: annotation
                prefix: Gedmo\Translatable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
                is_bundle: false
            gedmo_translator:
                type: annotation
                prefix: Gedmo\Translator\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
                alias: GedmoTranslator # this one is optional and will default to the name set for the mapping
                is_bundle: false
            gedmo_loggable:
                type: annotation
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
                is_bundle: false
            gedmo_tree:
                type: annotation
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                alias: GedmoTree # this one is optional and will default to the name set for the mapping
                is_bundle: false
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"

mopa_bootstrap:
    form:
        show_legend: true # default is true
        show_child_legend: true # default is true
        error_type: inline # or inline which is default

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Up2green\UserBundle\Entity\User

sonata_admin:
    title:      Up2green administration
    title_logo: /favicon.png

    dashboard:
        groups:
            Association: []
            Education: []
            Reforestation: []
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }
knp_menu:
    twig: true

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.rss:

jms_payment_core:
    secret: up2greenSup3erM3GAs2cret

jms_payment_paypal:
    username: 'antoine.gerigne_api1.up2green.com'
    signature: 'AFbF3MLf8s8cAfgEC3-ZHq3jtLkAAg5billJSDcrHR0jhWshMoGmx3bP'
    password: 'EH6S97W3Q2W7HTWR'
    debug: false

jms_i18n_routing:
    default_locale: %locale%
    locales: %locales%
    strategy: prefix_except_default

craue_twig_extensions: ~

ornicar_gravatar:
    rating: g
    size: 80

liip_imagine:
    # FIXME the cache clearer is bugged
    cache_prefix:         /uploads/cache
    cache_clearer: false
    filter_sets:
        thumb_75x75_outbound:
            quality: 75
            filters:
                thumbnail: { size: [75, 75], mode: outbound }
        thumb_130x130_outbound:
            quality: 75
            filters:
                thumbnail: { size: [130, 130], mode: outbound }
        thumb_250x250_outbound:
            quality: 75
            filters:
                thumbnail: { size: [250, 250], mode: outbound }

bazinga_geocoder:
    providers:
        google_maps: ~

a2lix_translation_form:
    locales: %locales%
    default_required: false

up2green_education:
    trees_by_kit: 35
    kit_price: 150