imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem

web_profiler:
    toolbar: true
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

parameters:
    domain: localhost