imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: fr }
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  fr
    trust_proxy_headers: false
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'MopaBootstrapBundle:Form:fields.html.twig'

services:
    twig.extension.debug:
        class: Twig_Extensions_Extension_Debug
        tags:
            - { name: 'twig.extension' }

    up2green.kernel.event_listener.locale:
        class: Up2green\CommonBundle\HttpKernel\EventListener\LocaleListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
        @arguments:
            - { defaultLocale: %default_locale% }

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        sass:
            bin: /var/lib/gems/1.8/gems/sass-3.1.15/bin/sass
            compass: /var/lib/gems/1.8/gems/compass-0.12.1/bin/compass
        cssrewrite: ~
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        less:
            node: /usr/local/bin/node
            node_paths: [/usr/local/lib/node_modules]
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar

propel:
    path:       "%kernel.root_dir%/../vendor/propel/propel1"
    phing_path: "%kernel.root_dir%/../vendor/phing/phing"
    dbal:
        driver:               mysql
        user:                 %database_user%
        password:             %database_password%
        dsn:                  mysql:host=%database_host%;dbname=%database_name%;charset=UTF8
        options:              {}
        attributes:           {}

mopa_bootstrap:
    form:
        show_legend: true # default is true
        show_child_legend: true # default is true
        error_type: inline # or inline which is default

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

fos_user:
    db_driver: propel
    firewall_name: main
    user_class: FOS\UserBundle\Propel\User
