imports:
    - { resource: config_dev.yml }

propel:
    build_properties:
        propel.database.url: 'mysql:host=%database_host%;dbname=%database_name%_test;charset=UTF8'
    dbal:
#        driver:               pdo_sqlite
#        dsn:                  'sqlite::memory:'
        driver:               mysql
        dsn:                  'mysql:host=%database_host%;dbname=%database_name%_test;charset=UTF8'

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem

web_profiler:
    toolbar: true
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
