imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

swiftmailer:
    delivery_address: clement.gautier.76@gmail.com
    disable_delivery: true

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: WARNING
        firephp:
            type:  firephp
            level: info

assetic:
    use_controller: true

fos_user:
    firewall_name: dev

jms_payment_paypal:
    username: 'test_1306521590_biz_api1.up2green.com'
    signature: 'A.ZQCpvrRWwBbYXb9.MR7.zhHtKSA3R02020efHBK07kz.F.4nRihphP'
    password: '1306521599'
    debug: true
