parameters:
    database_driver:    pdo_mysql
    database_host:      localhost
    database_port:      ~
    database_name:      up2green2
    database_user:      username
    database_password:  "sm@rTp0wereD!pwd"

    mailer_transport:   smtp
    mailer_host:        localhost
    mailer_user:        ~
    mailer_password:    ~

    locale:             en

    secret:             up2green2TokenSecret
