Up2greenReforestationBundle:
    resource: "@Up2greenReforestationBundle/Controller/"
    type:     annotation
    prefix:   /reforestation

Up2greenSearchBundle:
    resource: "@Up2greenSearchBundle/Controller/"
    type:     annotation
    prefix:   /

Up2greenUserBundle:
    resource: "@Up2greenUserBundle/Controller/"
    type:     annotation
    prefix:   /user

Up2greenCommonBundle:
    resource: "@Up2greenCommonBundle/Controller/"
    type:     annotation
    prefix:   /

Up2greenBlogBundle:
    resource: "@Up2greenBlogBundle/Controller/"
    type:     annotation
    prefix:   /
    prefix:   /blog

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
