up2green_admin:
    resource: "@Up2greenAdminBundle/Resources/config/routing.yml"
    prefix:   /
    host:     admin.{domain}
    requirements:
        domain: %domain%

up2green_education:
    resource: "@Up2greenEducationBundle/Controller/"
    type:     annotation
    prefix:   /
    host:     education.{domain}
    requirements:
        domain: %domain%

up2green_reforestation:
    resource: "@Up2greenReforestationBundle/Controller/"
    type:     annotation
    prefix:   /
    host:     reforestation.{domain}
    requirements:
        domain: %domain%

up2green_blog:
    resource: "@Up2greenBlogBundle/Controller/"
    type:     annotation
    prefix:   /
    host:     association.{domain}
    requirements:
        domain: %domain%

up2green_user:
    resource: "@Up2greenUserBundle/Controller/"
    type:     annotation
    prefix:   /user

up2green_search:
    resource: "@Up2greenSearchBundle/Controller/"
    type:     annotation
    prefix:   /
    host:     www.{domain}
    requirements:
        domain: %domain%

up2green_common:
    resource: "@Up2greenCommonBundle/Controller/"
    type:     annotation
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_imagine:
    resource: .
    type:     imagine

_assetic:
    resource: .
    type:     assetic

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile