Up2green\EducationBundle\Model\Classroom:
    properties:
        year:
            - NotBlank: ~
            - Type:
                type: integer
        description:
            - MaxLength: 2000
        name:
            - NotBlank: ~
            - MaxLength: 30
        pictureFile:
            - Image: ~

Up2green\EducationBundle\Model\WaitingList:
    properties:
        first_name:
            - NotBlank: ~
        last_name:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email:
                message: The email "{{ value }}" is not a valid email.
                checkMX: true
        phone_number:
            - NotBlank: ~
        kits_number:
            - NotBlank: ~
            - Type:
                type: integer

Up2green\EducatuinBundle\DomainObject\Registration:
    constraints:
        - Callback:
            methods:
                - [Up2green\CommonBundle\Model\Voucher, isValid]
