Up2green\EducationBundle\Model\Classroom:
    properties:
        year:
            - NotBlank: ~
            - Type:
                type: integer
        description:
            - Length:
                max: 2000
        name:
            - NotBlank: ~
            - Length:
                max: 30
        uploadedFile:
            - Image: ~

Up2green\EducationBundle\Model\WaitingList:
    properties:
        first_name:
            - NotBlank: ~
        last_name:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email:
                message: The email "{{ value }}" is not a valid email.
                checkMX: true
        phone_number:
            - NotBlank: ~
        kits_number:
            - NotBlank: ~
            - Type:
                type: integer