Up2green\CommonBundle\Model\Address:
    properties:
        name:
            - NotBlank: ~
        street_line_1:
            - NotBlank: ~
            - Length:
                max: 50
        street_line_2:
            - Length:
                max: 50
        zipcode:
            - NotBlank: ~
            - Type:
                type: integer
        city:
            - NotBlank: ~
        country:
            - NotBlank: ~

Up2green\CommonBundle\Model\Voucher:
    properties:
        code:
            - NotBlank: { groups: [use] }
    constraints:
        - Callback:
            methods:
                - [Up2green\CommonBundle\Model\Voucher, isValid]
            groups: [use]
