generator: admingenerator.generator.propel
params:
  model: Up2green\BlogBundle\Model\Article
  namespace_prefix: Up2green
  bundle_name: AdminBundle
  fields: ~

builders:
  list:
    params:
      title: List for AdminBundle
      display: ~
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: ~
  new:
    params:
      title: New object for AdminBundle
      display: ~
      actions:
        list: ~
  edit:
    params:
      title: You're editing the object "{{ YourModel.title }}"
      display: ~
      actions:
        list: ~
  delete: ~
