generator: admingenerator.generator.propel
params:
  model: Up2green\EducationBundle\Model\EducationVoucher
  namespace_prefix: Up2green
  bundle_name: AdminBundle
  fields:
    voucher:
      formType: \Up2green\AdminBundle\Form\Type\VoucherType

builders:
  list:
    batch_actions:
      delete: ~ # Pre coded action
    params:
      title: List of education vouchers
      display: [id, code]
      actions:
        new: ~
      object_actions:
        delete: ~
  new:
    params:
      title: New education voucher
      display:
        General: [voucher]
      actions:
        list: ~
  edit:
    params:
      title: Edit education voucher "%EducationVoucher%"
      display:
        General: [voucher]
      actions:
        list: ~
  filters:
    params:
      display: ~
  delete: ~
