up2green_admin_homepage:
    pattern:   /
    defaults:  { _controller: Up2greenAdminBundle:Default:index }

up2green_admin_school:
    resource: "@Up2greenAdminBundle/Controller/School/"
    type:     admingenerator
    prefix:   /admin/school

up2green_admin_classroom:
    resource: "@Up2greenAdminBundle/Controller/Classroom/"
    type:     admingenerator

up2green_admin_waitingList:
    resource: "@Up2greenAdminBundle/Controller/WaitingList/"
    type:     admingenerator
    prefix:   /admin/waiting-list
